<footer class="footer">
  <!-- Back to top button -->
  <a href="#" class="stt" title="scroll to top"></a>
  <div class="footer-left">
    <!-- Social media links and email -->
    <a href="https://twitter.com/" class="footer-button">Twitter</a>
    <a href="https://www.linkedin.com/" class="footer-button">LinkedIn</a>
    <a href="https://discord.com/" class="footer-button">Discord</a>
    <a href="mailto:104762184@student.swin.edu.au" class="footer-button"
      >Email</a
    >
  </div>
  <div class="footer-right">
    <!-- Privacy policy and terms of use -->
    <a
      href="media/australian-privacy-principles.pdf"
      download="Privacy.pdf"
      class="footer-button"
      >Privacy</a
    >
    <button class="footer-button">Terms of Use</button>
    <!-- Copyright information -->
    <div class="copyright">©2024 Auris AI</div>
  </div>
</footer>
