<header class="SiteHeader_core">
  <div class="SiteHeader_wrapper">
    <!-- Logo and tagline -->
    <div class="logo">
      Auris AI
      <span>Next Generation AI</span>
    </div>
    <!-- Header buttons -->
    <div class="header-buttons">
      <a href="./apply.php" class="header-button">Apply</a>
      <a href="./about.php" class="header-button">About</a>
    </div>
  </div>
</header>
