<!-- Navigation section -->
<section class="web-navigator-container">
  <div class="web-navigator">
    <!-- Navigation buttons -->
    <a href="./index.php" class="button-white">Home</a>
    <a href="./jobs.php" class="button-white">Jobs</a>
    <a href="./apply.php" class="button-white">Apply</a>
    <a href="./about.php" class="button-white">About</a>
    <a href="./enhancements.php" class="button-white">Enhancements</a>
    <a href="./login.php" class="button-white">MANAGE</a>
    <a href="./phpenhancements.php" class="button-white">Enhancements 2</a>
    <a href="https://www.youtube.com/watch?v=POhqLPCJ0IY" class="button-white"
      >VIDEO</a
    >
  </div>
</section>
